const logs = [
        "[ OK ]  Started systemd-ask-password-console.path - Dispatch Password Requests to Console Directory Watch.",
        "[ OK ]  Started systemd-ask-password-wall.path - Forward Password Requests to Wall Directory Watch.",
        "[ OK ]  Reached target cryptsetup.target - Local Encrypted Volumes.",
        "[ OK ]  Reached target integritysetup.target - Local Integrity Protected Volumes.",
        "[ OK ]  Reached target paths.target - Path Units.",
        "[ OK ]  Reached target slices.target - Slice Units.",
        "[ OK ]  Reached target swap.target - Swaps.",
        "[ OK ]  Reached target veritysetup.target - Local Verity Protected Volumes.",
        "        Starting fake-hwclock.service - Restore / save the current clock.....",
        "        Starting keyboard-setup.service - Set the console keyboard layout.....",
        "        Starting kmod-static-nodes.service - Create List of Static Device Nodes.....",
        "        Starting modprobe@configfs.service - Load Kernel Module configfs.....",
        "        Starting modprobe@dm_mod.service - Load Kernel Module dm_mod.....",
        "        Starting modprobe@drm.service - Load Kernel Module drm.....",
        "        Starting modprobe@efi_pstore.service - Load Kernel Module efi_pstore.....",
        "        Starting modprobe@fuse.service - Load Kernel Module fuse.....",
        "        Starting modprobe@loop.service - Load Kernel Module loop.....",
        "        Starting systemd-journald.service - Journal Service.....",
        "        Starting systemd-modules-load.service - Load Kernel Modules.....",
        "        Starting systemd-remount-fs.service - Remount Root and Kernel File Systems.....",
        "        Starting systemd-udev-trigger.service - Coldplug All udev Devices.....",
        "[ OK ]  Finished fake-hwclock.service - Restore / save the current clock.",
        "[ OK ]  Finished kmod-static-nodes.service - Create List of Static Device Nodes.",
        "[ OK ]  Finished modprobe@configfs.service - Load Kernel Module configfs.",
        "[ OK ]  Finished modprobe@dm_mod.service - Load Kernel Module dm_mod.",
        "[ OK ]  Finished modprobe@drm.service - Load Kernel Module drm.",
        "[ OK ]  Finished modprobe@efi_pstore.service - Load Kernel Module efi_pstore.",
        "[ OK ]  Finished keyboard-setup.service - Set the console keyboard layout.",
        "[ OK ]  Finished modprobe@fuse.service - Load Kernel Module fuse.",
        "[ OK ]  Finished modprobe@loop.service - Load Kernel Module loop.",
        "[ OK ]  Started systemd-journald.service - Journal Service.",
        "[ OK ]  Finished systemd-modules-load.service - Load Kernel Modules.",
        "[ OK ]  Finished systemd-remount-fs.service - Remount Root and Kernel File Systems.",
        "        Starting systemd-journal-flush.service - Flush Journal to Persistent Storage.....",
        "        Starting systemd-random-seed.service - Load/Save Random Seed.....",
        "        Starting systemd-sysctl.service - Apply Kernel Variables.....",
        "        Starting systemd-sysusers.service - Create System Users.....",
        "[ OK ]  Finished systemd-sysusers.service - Create System Users.",
        "[ OK ]  Finished systemd-sysctl.service - Apply Kernel Variables.",
        "[ OK ]  Finished systemd-random-seed.service - Load/Save Random Seed.",
        "        Starting systemd-tmpfiles-setup-dev.service - Create Static Device Nodes in /dev.....",
        "[ OK ]  Finished systemd-udev-trigger.service - Coldplug All udev Devices.",
        "        Starting ifupdown-pre.service - Helper to synchronize boot up for ifupdown.....",
        "[ OK ]  Finished systemd-journal-flush.service - Flush Journal to Persistent Storage.",
        "[ OK ]  Finished ifupdown-pre.service - Helper to synchronize boot up for ifupdown.",
        "[ OK ]  Finished systemd-tmpfiles-setup-dev.service - Create Static Device Nodes in /dev.",
        "[ OK ]  Reached target local-fs-pre.target - Preparation for Local File Systems.",
        "        Starting systemd-udevd.service - Rule-based Manager for Device Events and Files.....",
        "[ OK ]  Started systemd-udevd.service - Rule-based Manager for Device Events and Files.",
        "        Starting systemd-fsck@dev-disk-by\\x2dpartuuid-5407a75e\\x2d01.service - File System Check on /dev/disk/by-partuuid/5407a75e-01.....",
        "[ OK ]  Started systemd-fsckd.service - File System Check Daemon to report status.",
        "[ OK ]  Finished systemd-fsck@dev-disk-by\\x2dpartuuid-5407a75e\\x2d01.service - File System Check on /dev/disk/by-partuuid/5407a75e-01.",
        "[ OK ]  Reached target local-fs.target - Local File Systems.",
        "        Starting console-setup.service - Set console font and keymap.....",
        "        Starting networking.service - Raise network interfaces.....",
        "        Starting systemd-binfmt.service - Set Up Additional Binary Formats.....",
        "        Starting systemd-tmpfiles-setup.service - Create Volatile Files and Directories.....",
        "[ OK ]  Finished console-setup.service - Set console font and keymap.",
        "[ OK ]  Finished systemd-tmpfiles-setup.service - Create Volatile Files and Directories.",
        "        Starting systemd-timesyncd.service - Network Time Synchronization.....",
        "        Starting systemd-update-utmp.service - Record System Boot/Shutdown in UTMP.....",
        "[ OK ]  Finished systemd-binfmt.service - Set Up Additional Binary Formats.",
        "[ OK ]  Finished networking.service - Raise network interfaces.",
        "[ OK ]  Reached target rpc_pipefs.target.",
        "[ OK ]  Reached target nfs-client.target - NFS client services.",
        "[ OK ]  Reached target remote-fs-pre.target - Preparation for Remote File Systems.",
        "[ OK ]  Reached target remote-fs.target - Remote File Systems.",
        "[ OK ]  Finished systemd-update-utmp.service - Record System Boot/Shutdown in UTMP.",
        "        Starting systemd-rfkill.service - Load/Save RF Kill Switch Status.....",
        "        Starting modprobe@dm_mod.service - Load Kernel Module dm_mod.....",
        "        Starting modprobe@efi_pstore.service - Load Kernel Module efi_pstore.....",
        "        Starting modprobe@loop.service - Load Kernel Module loop.....",
        "[ OK ]  Started systemd-timesyncd.service - Network Time Synchronization.",
        "[ OK ]  Finished modprobe@dm_mod.service - Load Kernel Module dm_mod.",
        "[ OK ]  Reached target time-set.target - System Time Set.",
        "[ OK ]  Finished modprobe@efi_pstore.service - Load Kernel Module efi_pstore.",
        "[ OK ]  Finished modprobe@loop.service - Load Kernel Module loop.",
        "[ OK ]  Reached target sysinit.target - System Initialization.",
        "[ OK ]  Started apt-daily.timer - Daily apt download activities.",
        "[ OK ]  Started apt-daily-upgrade.timer - Daily apt upgrade and clean activities.",
        "[ OK ]  Started dpkg-db-backup.timer - Daily dpkg database backup timer.",
        "[ OK ]  Started e2scrub_all.timer - Periodic ext4 Online Metadata Check for All Filesystems.",
        "[ OK ]  Started fstrim.timer - Discard unused blocks once a week.",
        "[ OK ]  Started logrotate.timer - Daily rotation of log files.",
        "[ OK ]  Started man-db.timer - Daily man-db regeneration.",
        "[ OK ]  Started systemd-tmpfiles-clean.timer - Daily Cleanup of Temporary Directories.",
        "[ OK ]  Reached target timers.target - Timer Units.",
        "[ OK ]  Reached target sockets.target - Socket Units.",
        "[ OK ]  Reached target basic.target - Basic System.",
        "        Starting alsa-restore.service - Save/Restore Sound Card State.....",
        "        Starting avahi-daemon.service - Avahi mDNS/DNS-SD Stack.....",
        "[ OK ]  Started cron.service - Regular background program processing daemon.",
        "        Starting dbus.service - D-Bus System Message Bus.....",
        "        Starting dphys-swapfile.service - dphys-swapfile - set up, mount/unmount, and delete a swap file.....",
        "        Starting e2scrub_reap.service - Remove Stale Online ext4 Metadata Check Snapshots.....",
        "        Starting polkit.service - Authorization Manager.....",
        "        Starting raspi-config.service - LSB: Switch to ondemand cpu governor (unless shift key is pressed).....",
        "        Starting rpi-eeprom-update.service - Check for Raspberry Pi EEPROM updates.....",
        "        Starting sshswitch.service - Turn on SSH if /boot/ssh or /boot/firmware/ssh is present.....",
        "        Starting systemd-logind.service - User Login Management.....",
        "        Starting triggerhappy.service - triggerhappy global hotkey daemon.....",
        "[ OK ]  Started systemd-rfkill.service - Load/Save RF Kill Switch Status.",
        "[ OK ]  Finished alsa-restore.service - Save/Restore Sound Card State.",
        "[ OK ]  Started triggerhappy.service - triggerhappy global hotkey daemon.",
        "[ OK ]  Started Sep 03 19:43:32 condorpi polkitd[575]: Started polkitd version 122.",
        "[ OK ]  Finished sshswitch.service - Turn on SSH if /boot/ssh or /boot/firmware/ssh is present.",
        "[ OK ]  Started dbus.service - D-Bus System Message Bus.",
        "        Starting NetworkManager.service - Network Manager.....",
        "[ OK ]  Reached target sound.target - Sound Card.",
        "        Starting wpa_supplicant.service - WPA supplicant.....",
        "[ OK ]  Finished Sep 03 19:43:32 condorpi polkitd[575]: Finished loading, compiling and executing 4 rules.",
        "[ OK ]  Started avahi-daemon.service - Avahi mDNS/DNS-SD Stack.",
        "[ OK ]  Started polkit.service - Authorization Manager.",
        "[ OK ]  Finished dphys-swapfile.service - dphys-swapfile - set up, mount/unmount, and delete a swap file.",
        "        Starting ModemManager.service - Modem Manager.....",
        "[ OK ]  Started systemd-logind.service - User Login Management.",
        "[ OK ]  Started wpa_supplicant.service - WPA supplicant.",
        "[ OK ]  Finished rpi-eeprom-update.service - Check for Raspberry Pi EEPROM updates.",
        "[ OK ]  Started NetworkManager.service - Network Manager.",
        "[ OK ]  Reached target network.target - Network.",
        "        Starting NetworkManager-wait-online.service - Network Manager Wait Online.....",
        "        Starting ssh.service - OpenBSD Secure Shell server.....",
        "        Starting systemd-user-sessions.service - Permit User Sessions.....",
        "        Starting systemd-hostnamed.service - Hostname Service.....",
        "[ OK ]  Finished systemd-user-sessions.service - Permit User Sessions.",
        "[ OK ]  Started ModemManager.service - Modem Manager.",
        "[ OK ]  Finished e2scrub_reap.service - Remove Stale Online ext4 Metadata Check Snapshots.",
        "[ OK ]  Started systemd-hostnamed.service - Hostname Service.",
        "[ OK ]  Started ssh.service - OpenBSD Secure Shell server.",
        "        Starting NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service.....",
        "[ OK ]  Started raspi-config.service - LSB: Switch to ondemand cpu governor (unless shift key is pressed).",
        "[ OK ]  Started NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service.",
        "[ OK ]  Finished NetworkManager-wait-online.service - Network Manager Wait Online.",
        "[ OK ]  Reached target network-online.target - Network is Online.",
        "        Starting rc-local.service - /etc/rc.local Compatibility.....",
        "        Starting rpc-statd-notify.service - Notify NFS peers of a restart.....",
        "[ OK ]  Started rc-local.service - /etc/rc.local Compatibility.",
        "[ OK ]  Started getty@tty1.service - Getty on tty1.",
        "[ OK ]  Reached target getty.target - Login Prompts.",
        "[ OK ]  Reached target multi-user.target - Multi-User System.",
        "        Starting systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP.....",
        "[ OK ]  Started rpc-statd-notify.service - Notify NFS peers of a restart.",
        "[ OK ]  Finished systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP.",
        "        Starting user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.....",
        "[ OK ]  Finished user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.",
        "        Starting user@1000.service - User Manager for UID 1000.....",
        "[ OK ]  Started user@1000.service - User Manager for UID 1000.",
        "[ OK ]  Started session-1.scope - Session 1 of User Mariano.",
        "        Starting NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service.....",
        "[ OK ]  Started NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service.",
]

export default logs;
